---
- name: Validate SSH configuration
  ansible.builtin.command:
    cmd: /usr/sbin/sshd -t
  changed_when: false
  listen: Validate and reload SSH

- name: Reload SSH service
  ansible.builtin.service:
    name: "{{ sftp_service_name }}"
    state: reloaded
  listen: Validate and reload SSH

- name: Restart Apache
  ansible.builtin.service:
    name: httpd
    state: restarted